---
- name: Configure Apache.
  lineinfile:
    dest: "{{ apache_server_root }}/conf/{{ apache_daemon }}.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items: "{{ apache_ports_configuration_items }}"
  notify: restart apache

- name: Check whether certbot certificates defined in vhosts exist.
  stat: "path=/etc/letsencrypt/live/{{ item.servername }}/fullchain.pem"
  register: apache_ssl_certificates
  when: 
    - item.certbot is defined
    - item.certbot
  with_items: "{{ apache_vhosts_ssl }}"

- name: Check whether certificates defined in vhosts exist.
  stat: "path={{ item.certificate_file }}"
  register: apache_ssl_certificates
  when: (item.certbot is not defined) or (not item.certbot)
  with_items: "{{ apache_vhosts_ssl }}"

- name: Add apache vhosts configuration.
  template:
    src: "{{ apache_vhosts_template }}"
    dest: "{{ apache_conf_path }}/{{ apache_vhosts_filename }}"
    owner: root
    group: root
    mode: 0644
  notify: restart apache
  when: apache_create_vhosts
